name: b

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "21 4 * * 0"

permissions:
  contents: write
  
jobs:
  build_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time and date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"

    - name: Build Packages
      # uses: kopp/build-aur-packages@v1
      uses: vdun/build-aur-packages@master
      with:
        packages: >
          pacman-static
        # missing_pacman_dependencies: >
          # hello

    - name: List generated Files
      run: ls -1 > ${{ github.workspace }}/files.txt
    - name: Remove the current data from the release
      uses: kopp/action-delete-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: aurci2
    - name: Upload Files to Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: aurci2
        name: aurci build ${{ github.run_number }} from ${{ steps.date.outputs.date }}
        body: aurci build ${{ github.run_number }} from ${{ steps.date.outputs.date }}
        files: |
          ${{ github.workspace }}/*
        draft: false
        prerelease: false
